### ISSUE TITLE
python load failing

### ISSUE THREAD

**Issue by Starlight220** [Kotlin/kotlin-numpy#13]
The python loading script keeps failing. 
This is my code (for now):
`import org.jetbrains.numkt.arange`
`fun main() {
    val a = arange(4)
    println(a)
}`

and this is the error from running the code:
`Exception in thread "main" java.lang.Exception: "ERROR: Command errored out with exit status 1:
     command: 'C:\Program Files (x86)\Python38-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Yotam\\AppData\\Local\\Temp\\pip-install-fcpaxyxj\\ktnumpy\\setup.py'"'"'; __file__='"'"'C:\\Users\\Yotam\\AppData\\Local\\Temp\\pip-install-fcpaxyxj\\ktnumpy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Yotam\AppData\Local\Temp\pip-pip-egg-info-zderuhqa'
         cwd: C:\Users\Yotam\AppData\Local\Temp\pip-install-fcpaxyxj\ktnumpy\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Yotam\AppData\Local\Temp\pip-install-fcpaxyxj\ktnumpy\setup.py", line 67, in <module>
        include_dirs=get_java_includes() + ['src/main/ktnumpy/jni/include', get_numpy_include()]
      File "C:\Users\Yotam\AppData\Local\Temp\pip-install-fcpaxyxj\ktnumpy\buildScr\python\utils.py", line 76, in get_java_includes
        java_include = os.path.join(java_home, 'include')
      File "C:\Program Files (x86)\Python38-32\lib\ntpath.py", line 78, in join
        path = os.fspath(path)
    TypeError: expected str, bytes or os.PathLike object, not NoneType
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output." when executing the command: python -m pip install ktnumpy
	at org.jetbrains.numkt.LibraryLoader.execCommand(NativeLibUtils.kt:121)
	at org.jetbrains.numkt.LibraryLoader.loadLibraries(NativeLibUtils.kt:77)
	at org.jetbrains.numkt.Interpreter.initialize(Interpreter.kt:49)
	at org.jetbrains.numkt.Interpreter.access$initialize(Interpreter.kt:24)
	at org.jetbrains.numkt.Interpreter$Companion.getInterpreter(Interpreter.kt:31)
	at org.jetbrains.numkt.UtilsKt.callFunc(Utils.kt:38)
	at org.jetbrains.numkt.UtilsKt.callFunc$default(Utils.kt:36)
	at LearningKNumpyKt.main(LearningKNumpy.kt:10)
	at LearningKNumpyKt.main(LearningKNumpy.kt)`

I would be happy to give extra details/try some commands if needed.

**Comment by devcrocod** [comment]
Do you have python 3.8?
If you have python 3.8, try to run again

**Comment by Starlight220** [comment]
> Do you have python 3.8?

I installed python 3.8.2 from the python website, should it be installed from the Microsoft store?

> If you have python 3.8, try to run again

I opened this issue after trying to run it many, many times, including running the command itself in the terminal.

**Comment by devcrocod** [comment]
> I installed python 3.8.2 from the python website, should it be installed from the Microsoft store?

No, installing from the Microsoft store is not recommended. Users have Microsoft Home and python from the store have limited permissions.

I published a new wheel for python 3.8 on pypi, so I asked you to run it again. You can also install the native library yourself with [pypi](https://pypi.org/project/ktnumpy/0.1.4/). And please check if you have python in path.

Please let me know if succeeded to run.

**Comment by Starlight220** [comment]
> Please let me know if succeeded to run.

I reinstalled python, and ran the program again, it failed with a `NoSuchMethodError`:
```
Exception in thread "main" java.lang.NoSuchMethodError: <init>
	at org.jetbrains.numkt.Interpreter.callFunc$kotlin_numpy(Native Method)
	at org.jetbrains.numkt.UtilsKt.callFunc(Utils.kt:38)
	at org.jetbrains.numkt.UtilsKt.callFunc$default(Utils.kt:36)
	at LearningKNumpyKt.main(LearningKNumpy.kt:11)
	at LearningKNumpyKt.main(LearningKNumpy.kt)
```

**Comment by devcrocod** [comment]
Use the "clear" option in gradle and try to run the IDE with root access.
Please also send the output of the following command in the terminal `pip show ktnumpy` or `python -m pip show ktnumpy`, to make sure that the native library is installed correctly.

**Comment by Starlight220** [comment]
> Use the "clear" option in gradle and try to run the IDE with root access.

Running IntelliJ as admin failed for the same reasons (`NoSuchMethodError`).

> Please also send the output of the following command in the terminal `pip show ktnumpy` or `python -m pip show ktnumpy`, to make sure that the native library is installed correctly.
``` 
> python -m pip show ktnumpy
Name: ktnumpy
Version: 0.1.4
Summary: Kotlin bindings for Numpy
Home-page: https://github.com/Kotlin/kotlin-numpy
Author: JetBrains
Author-email: UNKNOWN
License: Apache 2.0
Location: c:\users\yotam\appdata\local\programs\python\python38\lib\site-packages
Requires: numpy
Required-by:
```

**Comment by devcrocod** [comment]
What version of kotlin are you using?

**Comment by Starlight220** [comment]
I believe I'm using the default IntelliJ Kotlin SDK (1.3.71).

**Comment by devcrocod** [comment]
This error: https://youtrack.jetbrains.com/issue/KT-23366

In this case, please update Kotlin to 1.3.72, if you use IDEA this can be done in "Preferences" and specify the new version in gradle. If possible, build a new project for a clean experiment.

**Comment by Starlight220** [comment]
I opened a clean project, and it worked. Thanks for the help!
