### ISSUE TITLE
how to convert List or Array to KtNDArray

### ISSUE THREAD

**Issue by pengyuan-zhou** [Kotlin/kotlin-numpy#20]
Hi,

How to convert normal Kotlin List or Array to KtNDArray  and vice-versa ?

Thanks.

**Comment by devcrocod** [comment]
Hi,

To create an `KtNDArray` from an array or from a list, you can use the [array](https://kotlin.github.io/kotlin-numpy/kotlin-numpy/org.jetbrains.numkt/array.html) method.
To vice versa from `KtNDArray` to list there are methods [toList](https://kotlin.github.io/kotlin-numpy/kotlin-numpy/org.jetbrains.numkt.core/-kt-n-d-array/to-list.html), [toList2d](https://kotlin.github.io/kotlin-numpy/kotlin-numpy/org.jetbrains.numkt.core/-kt-n-d-array/to-list2d.html), [toList3d](https://kotlin.github.io/kotlin-numpy/kotlin-numpy/org.jetbrains.numkt.core/-kt-n-d-array/to-list3d.html).
 
Hope I helped you.

**Comment by pengyuan-zhou** [comment]
> Hi,
> 
> To create an `KtNDArray` from an array or from a list, you can use the [array](https://kotlin.github.io/kotlin-numpy/kotlin-numpy/org.jetbrains.numkt/array.html) method.
> To vice versa from `KtNDArray` to list there are methods [toList](https://kotlin.github.io/kotlin-numpy/kotlin-numpy/org.jetbrains.numkt.core/-kt-n-d-array/to-list.html), [toList2d](https://kotlin.github.io/kotlin-numpy/kotlin-numpy/org.jetbrains.numkt.core/-kt-n-d-array/to-list2d.html), [toList3d](https://kotlin.github.io/kotlin-numpy/kotlin-numpy/org.jetbrains.numkt.core/-kt-n-d-array/to-list3d.html).
> 
> Hope I helped you.

It worked, thank you !
